FROM redis:alpine

# If you need to add custom configuration, you can COPY it here
# COPY redis.conf /usr/local/etc/redis/redis.conf
# CMD [ "redis-server", "/usr/local/etc/redis/redis.conf" ]

EXPOSE 6379

CMD ["redis-server"]
